name: 'Prettier'
description: 'Format source code with Prettier'
inputs:
  path:
    description: "The file/glob to format"
    required: false
    default: '.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
