on: [push]
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./ # Uses an action in the root directory
        with:
          path: ./examples
