on: [push]
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./ # Uses an action in the root directory
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        # with:
        #   path: ./examples/**/*.{js,md}
